### PR TITLE
Allow multi-line table cell

### PR DESCRIPTION
**Pull request by wwwouter**

### CODE REVIEW

**Comment by aguingand** [comment]
I would prefer to only allow <br> instead of converting paragraphs

**Comment by wwwouter** [comment]
I'm just started looking into this, therefore I'm not sure what you mean exactly.

My current situation is that I'm using `@mantine/tiptap` with `tiptap-markdown` and `{html:false}` as option.
When a user creates a table (button that calls `editor.chain().focus().insertTable({ rows: 1, cols: 1 }).run()`) and presses enter in a table call, another ProseMirror node is created with the type 'paragraph' 
Because of `cell.childCount > 1` in `src/extensions/nodes/table.js` the table is marked as non-serializable and `[table]` is outputted in the resulting Markdown.

Do you propose that a user presses `Cmd-Enter` instead of just `Enter` in the table cell?

**Comment by aguingand** [comment]
You should enable `html` option if you use tables, `<br>` works if you press `Cmd+Enter`

**Comment by wwwouter** [comment]
I don't think I'll be able to educate all our users no to use the `Enter` key while editing. Also allowing html is something that is not preferable. 

But I understand that you don't see this as problem. I do wish to "fix" this myself. 

Do you know if I can do some preprocessing (collapsing the paragraphs down to one) before this package does the parsing, or maybe a easy way to override `src/extensions/nodes/table.js`?

I'd like to keep using this package, instead of creating a fork.

**Comment by aguingand** [comment]
You can customize the table serializing logic :
```js
new Editor({
  extension: [
    Table.extend({
      addStorage() {
        return {
          markdown: {
            serialize(state, node, parent) {
              // ...
            }
          }
        }
      }
    })
  ]
})
```
But be aware this may break in future version

**Pull request closed without merging**
